module.exports = {
  'src/routes/auth.js': '/api/auth',
  'src/routes/user.js': '/api/user',
  'src/routes/wallet.js': '/api/wallet',
  'src/routes/vtpass.js': '/api/vtpass',
  'src/routes/paystack.js': '/api/paystack',
  'src/routes/paystackVA.js': '/api/paystack',
  'src/routes/monnify.js': '/api/monnify',
  'src/routes/payment.js': '/api/payment',
  'src/routes/funding.js': '/api/funding',
  'src/routes/escrow.js': '/api/escrow',
  'src/routes/provider.js': '/api/provider',
  'src/routes/sessions.js': '/api/sessions',
  'src/routes/live.js': '/api/live',
  'src/routes/discovery.js': '/api/discovery',
  'src/routes/sms.js': '/api/sms',
  'src/routes/admin.js': '/api/admin',
  'src/routes/adminFundingControl.js': '/api/admin/funding',
  'src/routes/adminWithdrawals.js': '/api/admin',
  'src/routes/adminAudit.js': '/api/admin',
  'src/routes/adminReconcile.js': '/api/admin',
};
